name: DAST - idor

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      working-directory: idor
      run: npm install || true   # handles cases where package.json doesn't exist

    - name: Start IDOR app on port 3000
      working-directory: idor
      run: node server.js &

    - name: Wait for server
      run: |
        for i in {1..20}
        do
          if nc -z localhost 3000; then
            echo "IDOR API server is up!"
            exit 0
          fi
          echo "Waiting for IDOR API server..."
          sleep 3
        done
        echo "IDOR API failed to start"
        exit 1

    - name: OWASP ZAP full scan
      uses: zaproxy/action-full-scan@v0.8.0
      with:
        target: http://localhost:3000
